# Generated by Django 5.2.5 on 2025-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('UNKNOWN', '미정'), ('RESTAURANT', '식당'), ('HOSPITAL', '병원'), ('CAFE', '카페')], default='UNKNOWN', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
