# Generated by Django 5.2.5 on 2025-08-17 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(choices=[('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('purple', '보라'), ('pink', '핑크')], default='red', max_length=15)),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('relatedUrl', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritegroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favoriteGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteitem', to='markets.favoritegroup')),
                ('marketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteitem', to='markets.market')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
