# Generated by Django 5.2.5 on 2025-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_favoritegroup_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
