# Generated by Django 5.2.5 on 2025-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_market_telephone_market_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritegroup',
            name='color',
            field=models.CharField(choices=[('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('purple', '보라'), ('pink', '핑크')], default='blue', max_length=15),
        ),
    ]
