# Generated by Django 5.2.5 on 2025-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_favoritegroup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-18 15:00:00'),
            preserve_default=False,
        ),
    ]
