# Generated by Django 5.2.5 on 2025-08-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_image'),
        ('markets', '0005_favoriteitem_createdat'),
    ]

    operations = [
    ]
