# Generated by Django 5.2.5 on 2025-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_merge_0004_image_0005_favoriteitem_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
