# Generated by Django 5.2.5 on 2025-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_merge_0004_image_0005_favoriteitem_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='business_hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
