# Generated by Django 5.2.5 on 2025-08-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_market_business_hours_alter_market_url'),
        ('markets', '0007_market_embedding'),
    ]

    operations = [
    ]
