# Generated by Django 5.2.5 on 2025-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sprotsLeisurePreference',
        ),
        migrations.AddField(
            model_name='user',
            name='sportsLeisurePreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cafePreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leisureCulturePreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='localInfrastructure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='localLivingExperience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurantPreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
