# Generated by Django 5.2.5 on 2025-08-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_sprotsleisurepreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relocationDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
