# Generated by Django 5.2.5 on 2025-08-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignedlevel', models.IntegerField()),
                ('assignedindex', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('requireverification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('requireverification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLevelMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', '미션 완료'), ('in_progress', '미션 진행 중'), ('waiting', '미션 시작 대기'), ('not_available', '미션 시작 불가')], default='not_available', max_length=15)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountlevelmission', to=settings.AUTH_USER_MODEL)),
                ('levelmissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountlevelmission', to='missions.levelmission')),
            ],
        ),
        migrations.CreateModel(
            name='AccountWeeklyMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', '미션 완료'), ('in_progress', '미션 진행 중'), ('waiting', '미션 시작 대기')], default='waiting', max_length=15)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountweeklymission', to=settings.AUTH_USER_MODEL)),
                ('weeklymissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountweeklymission', to='missions.weeklymission')),
            ],
        ),
    ]
