# Generated by Django 5.2.5 on 2025-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignedlevel', models.IntegerField()),
                ('assignedindex', models.IntegerField()),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
