# Generated by Django 5.2.5 on 2025-08-17 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmission',
            name='requireverification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklymission',
            name='requireverification',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountLevelMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', '미션 완료'), ('in_progress', '미션 진행 중'), ('waiting', '미션 시작 대기'), ('not_available', '미션 시작 불가')], default='not_available', max_length=15)),
                ('startedAt', models.DateTimeField()),
                ('completedAt', models.DateTimeField()),
                ('levelmissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountlevelmission', to='missions.levelmission')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountlevelmission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountWeeklyMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', '미션 완료'), ('in_progress', '미션 진행 중'), ('waiting', '미션 시작 대기')], default='not_available', max_length=15)),
                ('startedAt', models.DateTimeField()),
                ('completedAt', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountweeklymission', to=settings.AUTH_USER_MODEL)),
                ('weeklymissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountweeklymission', to='missions.weeklymission')),
            ],
        ),
    ]
