# Generated by Django 5.2.5 on 2025-08-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_levelmission_requireverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlevelmission',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountlevelmission',
            name='startedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountweeklymission',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountweeklymission',
            name='startedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
