# Generated by Django 5.1.7 on 2025-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_accountlevelmission_completedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountweeklymission',
            name='status',
            field=models.CharField(choices=[('completed', '미션 완료'), ('in_progress', '미션 진행 중'), ('waiting', '미션 시작 대기')], default='waiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='levelmission',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklymission',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
