# Generated by Django 5.1.7 on 2025-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_accountweeklymission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmission',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
