# Generated by Django 5.2.5 on 2025-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_alter_levelmission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmission',
            name='reward_xp',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklymission',
            name='reward_xp',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
