# Generated by Django 5.2.5 on 2025-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_levelmission_reward_xp_weeklymission_reward_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmission',
            name='category',
            field=models.CharField(choices=[('heart', '즐겨찾기 관련'), ('like', 'ai 추천 관련'), ('pencil', '리뷰 관련'), ('map', '방문 인증 관련'), ('person', '소셜 기능 관련'), ('facility', '생활기관 관련'), ('cafe', '카페 관련'), ('restaurant', '레스토랑 관련'), ('book', '책 관련'), ('review', '리뷰 관련2')], default='heart', max_length=15),
        ),
    ]
